import Foundation

/// Decides which pasteboard changes are allowed into history.
///
/// Password-manager and concealed types are always ignored. A copy Stow itself
/// writes is marked and ignored, so a paste does not become another history row.
enum PasteboardPolicy {
    /// Never stored, and not removable in Settings.
    static let alwaysIgnored: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        originType,
    ]

    static let originType = "com.nehangpatel.stow.origin"

    /// Apple marks Continuity / Universal Clipboard payloads with this type.
    static let universalClipboardType = "com.apple.is-remote-clipboard"

    static let supported: Set<String> = [
        "public.utf8-plain-text",
        "public.rtf",
        "public.html",
        "public.png",
        "public.tiff",
        "public.file-url",
        "public.url",
    ]

    /// True when this change must not be read into the database.
    static func shouldIgnore(types: Set<String>, extraIgnored: Set<String> = []) -> Bool {
        let ignored = alwaysIgnored.union(extraIgnored)
        if !types.isDisjoint(with: ignored) {
            return true
        }
        return types.isDisjoint(with: supported)
    }

    /// True when the pasteboard change arrived from another Apple device.
    static func isUniversalClipboard(types: Set<String>) -> Bool {
        types.contains(universalClipboardType)
    }
}
