import XCTest

final class PasteboardPolicyTests: XCTestCase {
    func testPlainTextIsKept() {
        XCTAssertFalse(PasteboardPolicy.shouldIgnore(types: ["public.utf8-plain-text"]))
    }

    func testConcealedTextIsIgnored() {
        let types: Set<String> = ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]
        XCTAssertTrue(PasteboardPolicy.shouldIgnore(types: types))
    }

    func testTransientAndAutoGeneratedAreIgnored() {
        XCTAssertTrue(PasteboardPolicy.shouldIgnore(types: ["public.utf8-plain-text", "org.nspasteboard.TransientType"]))
        XCTAssertTrue(PasteboardPolicy.shouldIgnore(types: ["public.png", "org.nspasteboard.AutoGeneratedType"]))
    }

    func testPasswordManagerTypesAreIgnored() {
        XCTAssertTrue(PasteboardPolicy.shouldIgnore(types: ["public.utf8-plain-text", "com.agilebits.onepassword"]))
        XCTAssertTrue(PasteboardPolicy.shouldIgnore(types: ["public.utf8-plain-text", "net.antelle.keeweb"]))
    }

    func testOwnWritesAreIgnored() {
        XCTAssertTrue(PasteboardPolicy.shouldIgnore(types: ["public.utf8-plain-text", PasteboardPolicy.originType]))
    }

    func testUnsupportedTypesAreIgnored() {
        XCTAssertTrue(PasteboardPolicy.shouldIgnore(types: ["dyn.example", "com.unknown"]))
        XCTAssertTrue(PasteboardPolicy.shouldIgnore(types: []))
    }

    func testExtraIgnoredType() {
        XCTAssertTrue(
            PasteboardPolicy.shouldIgnore(
                types: ["public.utf8-plain-text", "com.example.secret"],
                extraIgnored: ["com.example.secret"]
            )
        )
    }

    func testUniversalClipboardMarker() {
        let remote: Set<String> = ["public.utf8-plain-text", PasteboardPolicy.universalClipboardType]
        XCTAssertTrue(PasteboardPolicy.isUniversalClipboard(types: remote))
        XCTAssertFalse(PasteboardPolicy.shouldIgnore(types: remote))
        XCTAssertFalse(PasteboardPolicy.isUniversalClipboard(types: ["public.utf8-plain-text"]))
    }
}
